import type { ParticleParams, PresetId, QualityProfile } from "./types";

export const DEFAULT_PARTICLE_PARAMS: ParticleParams = {
  brightnessThreshold: 0.06,
  contrast: 1.2,
  edgeStrength: 0.62,
  alphaThreshold: 0.05,
  density: 0.78,
  particleSize: 1.24,
  scatter: 0.11,
  driftSpeed: 0.04,
  depthStrength: 1.45,
  depthSmoothing: 0.45,
  depthLayers: 48,
  autoRotate: false,
  rotationSpeed: 0.25,
  bloomStrength: 0,
  bloomRadius: 0.24,
  bloomThreshold: 0.78,
  backgroundColor: "#000000",
  cameraDistance: 4,
  saturation: 0.92,
  waveStrength: 0.018,
  waveScale: 3,
  waveSpeed: 0.36,
  invasionRange: 0.46,
  edgeSoftness: 0.2,
  irregularity: 0.63,
  noiseScale: 4.8,
  outerDispersion: 1.08,
  colorRetention: 0.46,
};

export const PARTICLE_PRESETS: Record<PresetId, ParticleParams> = {
  portrait: {
    ...DEFAULT_PARTICLE_PARAMS,
    density: 0.84,
    particleSize: 1.1,
    edgeStrength: 0.54,
    scatter: 0.09,
    depthStrength: 1.32,
    invasionRange: 0.32,
    edgeSoftness: 0.23,
    colorRetention: 0.78,
    bloomStrength: 0,
    bloomThreshold: 0.74,
  },
  landscape: {
    ...DEFAULT_PARTICLE_PARAMS,
    density: 0.72,
    particleSize: 1,
    contrast: 1.14,
    edgeStrength: 0.49,
    depthStrength: 2.15,
    depthSmoothing: 0.58,
    invasionRange: 0.36,
    irregularity: 0.42,
    outerDispersion: 0.86,
    colorRetention: 0.74,
  },
  neon: {
    ...DEFAULT_PARTICLE_PARAMS,
    contrast: 1.46,
    saturation: 0.44,
    density: 0.66,
    particleSize: 1.38,
    scatter: 0.06,
    driftSpeed: 0.025,
    waveStrength: 0.013,
    invasionRange: 0.68,
    edgeSoftness: 0.13,
    irregularity: 0.86,
    noiseScale: 6.8,
    outerDispersion: 1.42,
    colorRetention: 0.16,
    bloomStrength: 0,
    bloomRadius: 0.34,
    bloomThreshold: 0.68,
  },
  mono: {
    ...DEFAULT_PARTICLE_PARAMS,
    saturation: 0,
    contrast: 1.52,
    edgeStrength: 0.74,
    density: 0.76,
    invasionRange: 0.5,
    edgeSoftness: 0.18,
    irregularity: 0.68,
    colorRetention: 0.34,
    bloomStrength: 0,
    bloomRadius: 0.3,
    bloomThreshold: 0.7,
  },
  reference: {
    ...DEFAULT_PARTICLE_PARAMS,
    brightnessThreshold: 0.08,
    contrast: 1.52,
    saturation: 0.22,
    density: 0.62,
    particleSize: 1.44,
    scatter: 0.05,
    driftSpeed: 0.02,
    depthStrength: 1.3,
    waveStrength: 0.012,
    waveScale: 4,
    waveSpeed: 0.24,
    invasionRange: 0.74,
    edgeSoftness: 0.11,
    irregularity: 0.9,
    noiseScale: 7.4,
    outerDispersion: 1.5,
    colorRetention: 0.1,
    bloomStrength: 0,
    bloomRadius: 0.38,
    bloomThreshold: 0.66,
  },
};

export const getQualityProfile = (mobile: boolean, devicePixelRatio: number): QualityProfile => mobile
  ? { maxParticles: 25_000, pixelRatio: 1, bloomScale: 0.6 }
  : {
      maxParticles: devicePixelRatio > 1.5 ? 120_000 : 60_000,
      pixelRatio: Math.min(devicePixelRatio, 2),
      bloomScale: 1,
    };

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

export const normalizeParams = (params: ParticleParams): ParticleParams => ({
  ...params,
  density: clamp(params.density, 0.05, 1),
  particleSize: clamp(params.particleSize, 0.6, 4.2),
  bloomStrength: clamp(params.bloomStrength, 0, 3),
  depthStrength: clamp(params.depthStrength, 0, 8),
  scatter: clamp(params.scatter, 0, 1.4),
  cameraDistance: clamp(params.cameraDistance, 2.5, 10),
  waveStrength: clamp(params.waveStrength, 0, 0.12),
  waveScale: clamp(params.waveScale, 0.8, 8),
  waveSpeed: clamp(params.waveSpeed, 0, 1.4),
  invasionRange: clamp(params.invasionRange, 0.1, 0.9),
  edgeSoftness: clamp(params.edgeSoftness, 0.04, 0.45),
  irregularity: clamp(params.irregularity, 0, 1),
  noiseScale: clamp(params.noiseScale, 1, 10),
  outerDispersion: clamp(params.outerDispersion, 0, 1.6),
  colorRetention: clamp(params.colorRetention, 0, 1),
});

export const STRUCTURAL_PARAM_KEYS = new Set<keyof ParticleParams>([
  "brightnessThreshold",
  "contrast",
  "edgeStrength",
  "alphaThreshold",
  "saturation",
  "density",
  "depthSmoothing",
  "depthLayers",
]);

export const requiresParticleRebuild = (before: ParticleParams, after: ParticleParams): boolean =>
  [...STRUCTURAL_PARAM_KEYS].some((key) => before[key] !== after[key]);
