import type { ParticleParams, PresetId, QualityProfile } from "./types";

export const DEFAULT_PARTICLE_PARAMS: ParticleParams = {
  effectMode: "portrait",
  dissolveDirection: "edge-in",
  dissolveProgress: 0.46,
  dissolveBandwidth: 0.24,
  brightnessThreshold: 0.06,
  contrast: 1.2,
  edgeStrength: 0.62,
  alphaThreshold: 0.05,
  density: 0.78,
  particleSize: 1.24,
  scatter: 0.11,
  driftSpeed: 0.04,
  depthStrength: 1.45,
  depthSmoothing: 0.45,
  depthLayers: 48,
  autoRotate: false,
  rotationSpeed: 0.25,
  bloomStrength: 0,
  bloomRadius: 0.24,
  bloomThreshold: 0.78,
  backgroundColor: "#000000",
  cameraDistance: 4,
  saturation: 0.92,
  waveStrength: 0.018,
  waveScale: 3,
  waveSpeed: 0.36,
  invasionRange: 0.46,
  edgeSoftness: 0.2,
  irregularity: 0.63,
  noiseScale: 4.8,
  outerDispersion: 1.08,
  colorRetention: 0.46,
  innerCrossStrength: 0.72,
};

export const PARTICLE_PRESETS: Record<PresetId, ParticleParams> = {
  portrait: {
    ...DEFAULT_PARTICLE_PARAMS,
    density: 0.84,
    particleSize: 1.1,
    edgeStrength: 0.54,
    scatter: 0.09,
    depthStrength: 1.32,
    invasionRange: 0.32,
    edgeSoftness: 0.23,
    colorRetention: 0.78,
    innerCrossStrength: 0.38,
    bloomStrength: 0,
    bloomThreshold: 0.74,
  },
  dust: {
    ...DEFAULT_PARTICLE_PARAMS,
    effectMode: "dust",
    dissolveDirection: "edge-in",
    dissolveProgress: 0.7,
    dissolveBandwidth: 0.3,
    density: 0.82,
    particleSize: 1.7,
    scatter: 0.057,
    driftSpeed: 0.08,
    waveStrength: 0.006,
    waveScale: 4.8,
    irregularity: 0.72,
    outerDispersion: 1.18,
    colorRetention: 0.7,
    innerCrossStrength: 0.58,
  },
  nebula: {
    ...DEFAULT_PARTICLE_PARAMS,
    effectMode: "nebula",
    dissolveDirection: "center-out",
    dissolveProgress: 0.52,
    dissolveBandwidth: 0.4,
    density: 0.76,
    particleSize: 1.5,
    scatter: 0.065,
    driftSpeed: 0.06,
    waveStrength: 0.009,
    waveScale: 3.8,
    waveSpeed: 0.28,
    irregularity: 0.82,
    outerDispersion: 1.42,
    colorRetention: 0.62,
    bloomStrength: 0.08,
    bloomRadius: 0.3,
    bloomThreshold: 0.78,
  },
  linear: {
    ...DEFAULT_PARTICLE_PARAMS,
    effectMode: "linear",
    dissolveDirection: "left-to-right",
    dissolveProgress: 0.5,
    dissolveBandwidth: 0.16,
    density: 0.78,
    particleSize: 1.3,
    scatter: 0.028,
    driftSpeed: 0.025,
    waveStrength: 0,
    irregularity: 0.24,
    noiseScale: 7.2,
    outerDispersion: 0.72,
    colorRetention: 0.82,
    innerCrossStrength: 0.42,
  },
  fog: {
    ...DEFAULT_PARTICLE_PARAMS,
    effectMode: "fog",
    dissolveDirection: "top-to-bottom",
    dissolveProgress: 0.55,
    dissolveBandwidth: 0.48,
    density: 0.72,
    particleSize: 1.18,
    scatter: 0.015,
    driftSpeed: 0.055,
    waveStrength: 0.004,
    waveScale: 3,
    waveSpeed: 0.22,
    irregularity: 0.9,
    noiseScale: 3.6,
    outerDispersion: 1.28,
    colorRetention: 0.66,
    innerCrossStrength: 0.5,
  },
  fire: {
    ...DEFAULT_PARTICLE_PARAMS,
    effectMode: "fire",
    dissolveDirection: "bottom-to-top",
    dissolveProgress: 0.58,
    dissolveBandwidth: 0.38,
    density: 0.82,
    particleSize: 1.36,
    scatter: 0.025,
    driftSpeed: 0.16,
    waveStrength: 0.018,
    waveScale: 7.2,
    waveSpeed: 0.82,
    irregularity: 0.78,
    noiseScale: 5.8,
    outerDispersion: 1.02,
    colorRetention: 0.56,
    innerCrossStrength: 0.62,
    bloomStrength: 0.16,
    bloomRadius: 0.22,
    bloomThreshold: 0.76,
  },
};

export const getQualityProfile = (mobile: boolean, devicePixelRatio: number): QualityProfile => mobile
  ? { maxParticles: 25_000, pixelRatio: 1, bloomScale: 0.6 }
  : {
      maxParticles: devicePixelRatio > 1.5 ? 120_000 : 60_000,
      pixelRatio: Math.min(devicePixelRatio, 2),
      bloomScale: 1,
    };

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

export const normalizeParams = (params: ParticleParams): ParticleParams => ({
  ...params,
  dissolveProgress: clamp(params.dissolveProgress, 0, 1),
  dissolveBandwidth: clamp(params.dissolveBandwidth, 0.06, 0.6),
  density: clamp(params.density, 0.05, 1),
  particleSize: clamp(params.particleSize, 0.6, 4.2),
  bloomStrength: clamp(params.bloomStrength, 0, 3),
  depthStrength: clamp(params.depthStrength, 0, 8),
  scatter: clamp(params.scatter, 0, 1.4),
  cameraDistance: clamp(params.cameraDistance, 2.5, 10),
  waveStrength: clamp(params.waveStrength, 0, 0.12),
  waveScale: clamp(params.waveScale, 0.8, 8),
  waveSpeed: clamp(params.waveSpeed, 0, 1.4),
  invasionRange: clamp(params.invasionRange, 0.1, 0.9),
  edgeSoftness: clamp(params.edgeSoftness, 0.04, 0.45),
  irregularity: clamp(params.irregularity, 0, 1),
  noiseScale: clamp(params.noiseScale, 1, 10),
  outerDispersion: clamp(params.outerDispersion, 0, 1.6),
  colorRetention: clamp(params.colorRetention, 0, 1),
  innerCrossStrength: clamp(params.innerCrossStrength, 0, 1),
});

export const STRUCTURAL_PARAM_KEYS = new Set<keyof ParticleParams>([
  "brightnessThreshold",
  "contrast",
  "edgeStrength",
  "alphaThreshold",
  "saturation",
  "depthSmoothing",
  "depthLayers",
]);

export const requiresParticleRebuild = (before: ParticleParams, after: ParticleParams): boolean =>
  [...STRUCTURAL_PARAM_KEYS].some((key) => before[key] !== after[key]);
